# Configure global settings in this section.
global:
  name: consul
  # Gossip encryption
  gossipEncryption:
    autoGenerate: true
# Configure your Consul servers in this section.
server:
  # Specify three servers that wait until all are healthy to bootstrap the Consul cluster.
  replicas: 3
  # Specify the resources that servers request for placement.
  resources:
    requests:
      memory: '256Mi'
      cpu: '250m'
    limits:
      memory: '512Mi'
      cpu: '500m'
# Configure Consul clients in this section
client:
  # Specify the resources that clients request for deployment.
  resources:
    requests:
      memory: '128Mi'
      cpu: '100m'
    limits:
      memory: '256Mi'
      cpu: '250m'
syncCatalog:
  enabled: true
# Enable and configure the Consul UI.
ui:
  enabled: true
  ingress:
    enabled: true
    ingressClassName: "nginx"
    hosts:
      - paths:
          - /
# Enable Consul connect pod injection
connectInject:
  enabled: true
  default: false
controller:
  enabled: true
